[package]
name = "rl"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Rusty reinforcement learning"
keywords = ["rl", "ml", "machine-learning", "ai"]
repository = "https://github.com/benbaarber/rl"

[features]
gym = ["dep:strum"]

[dependencies]
rand = "0.8.5"
strum = { version = "0.26.2", features = ["derive"], optional = true }

[dev-dependencies]
burn = { version = "0.13.1", features = ["wgpu", "autodiff"] }
